version: 0.1

phases:
  build:
    commands:
      - mvn package -Dmaven.test.skip=true
      - mv target/lottery-0.0.1-SNAPSHOT.jar lottery.jar
  post_build:
    commands:
artifacts:
  files:
    - lottery.jar